@echo off
echo Compiling main.js ...
jsminify main
echo Compiling update.js ...
jsminify update
echo Compiling networktables.js ...
jsminify networktables
echo Compiling background.js ...
jsminify background